name: Flatten Repo Folder

on:
  workflow_dispatch:

jobs:
  flatten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Move m7f-main contents to repo root
        run: |
          if [ -d "m7f-main" ]; then
            shopt -s dotglob
            mv m7f-main/* .
            rmdir m7f-main
          fi

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "نقل الملفات لجذر المستودع"
